/**
 * Shipped default recognition prompts per DT-xx (v5 matrix).
 * Used when creating a document type from a template — prompt mode by default;
 * users may switch to recognition signals in advanced mode if needed.
 */

export const DOCUMENT_TYPE_DEFAULT_PROMPTS: Record<string, string> = {
  "DT-01":
    "Vendor tax invoice for goods tied to a purchase order. Shows invoice number, invoice date, PO reference, line items with qty and prices, subtotal, tax, and total. Payable AP document from a supplier. Not a PO, GRN, proforma, credit note, or quote.",

  "DT-02":
    "Purchase order issued by the buyer to a vendor — lists ordered items, quantities, unit prices, currency, and terms. Supporting reference document for 3-way match; not a tax invoice and not a goods receipt. Often titled Purchase Order or PO.",

  "DT-03":
    "Goods receipt note, delivery docket, or proof-of-delivery showing received quantities against a PO. Supporting receipt document — no invoice totals or tax invoice wording. Not a vendor tax invoice, PO copy, or freight bill.",

  "DT-04":
    "Credit note or adjustment note from a vendor reducing a prior payable. References an original invoice or return reason; amounts are credits (negative adjustment). Not a standard payable invoice, debit note, or proforma.",

  "DT-05":
    "Debit note — either buyer-issued claim adjustment or vendor-issued additional charge. Adjusts payable up or documents a recovery; not a standard goods invoice or credit note. May reference shortages, quality claims, demurrage, or price escalation.",

  "DT-06":
    "Proforma invoice or advance/down-payment request before goods or services are delivered. Requests prepayment against PO or contract terms — not a valid tax invoice and must not be posted as final payable. Often says proforma or advance payment.",

  "DT-07":
    "Recurring or contract-based invoice: rent, lease, subscription, retainer, or periodic service billing. Shows service/billing period and contracted recurring amount. Not a one-off PO goods invoice, utility bill, or proforma advance request.",

  "DT-08":
    "Utility invoice for power, water, gas, telecom, or similar metered service. Shows account or meter number, consumption or usage, billing period, and charges. Not a goods PO invoice, freight bill, or generic vendor statement.",

  "DT-09":
    "Freight, logistics, or customs broker invoice. References shipment identifiers (AWB, bill of lading, container), freight charges, fuel surcharges, terminal fees, or broker disbursements. Not a commercial import dossier bundle or standard PO goods invoice.",

  "DT-10":
    "Import dossier member: commercial invoice, customs entry/import declaration, duty receipt, bill of lading/AWB, or packing list for cross-border goods. Part of an import clearance bundle — not a domestic PO invoice alone or a standalone freight broker fee note.",

  "DT-11":
    "Intercompany invoice between related legal entities in the same group. Names an IC partner, transfer-pricing or IC agreement reference, and mirrorable amounts. Not a third-party vendor invoice or employee expense claim.",

  "DT-12":
    "Employee expense claim or reimbursement with itemised receipts, categories, dates, and amounts. Submitted by an employee for out-of-pocket or policy expenses. Not a vendor tax invoice, corporate utility bill, or supplier PO invoice.",

  "DT-13":
    "Vendor statement of account listing open invoice references, ageing buckets, and running balance for a period. Reconciliation document only — never a tax invoice and must not be posted as payable. Not a remittance advice or dunning letter.",

  "DT-16":
    "Contract, rate card, statement of work, or lease agreement. Long-form legal/commercial terms, milestones, rates, escalation clauses; may include signature blocks. Supporting reference — not an invoice, PO, or GRN.",

  "DT-17":
    "Service entry sheet, timesheet, or completion certificate proving services rendered or hours approved. Supporting receipt for services — no invoice totals. Not a vendor tax invoice or purchase order.",

  "DT-18":
    "Remittance advice linking a payment to settled invoice references and amounts. Payment confirmation document — not a payable invoice, vendor statement, or dunning demand.",

  "DT-19":
    "Recipient-created tax invoice (RCTI) or self-billed invoice generated by the buyer from receipt/consumption data under an RCTI agreement. Tax document we issue — not a vendor-sent invoice for the same supply.",

  "DT-20":
    "Consignment or evaluated receipt settlement (ERS) settlement invoice triggered by consumption/withdrawal or auto-generated from GRN at PO price. Settlement under consignment/ERS agreement — not a standard PO goods invoice from an unsolicited vendor.",

  "DT-21":
    "One-time or ad-hoc vendor invoice from a supplier not yet fully onboarded, or a refund request. Standard invoice layout but highest fraud-risk class — may include bank detail change cues. Not a recurring contract invoice or employee claim.",

  "DT-22":
    "Dunning or payment reminder letter demanding payment on overdue invoice(s). Informational collections notice — not a tax invoice, credit note, or remittance advice. May reference penalty or disconnection.",

  "DT-23":
    "Bank or vendor detail change request proposing new payment bank account for a vendor. Master-data change letter or form — not a payable invoice. Never classify as a tax invoice even if on vendor letterhead.",

  "DT-24":
    "Quote, order acknowledgement, sales brochure, marketing material, or spam. Non-payable correspondence — must never be treated as a tax invoice. Often says quotation, estimate, or this is not a tax invoice.",

  "DT-25":
    "Tax authority document: GST assessment, ATO notice, or similar government tax notice. Issued by a revenue authority — routed to Tax team, not processed as a vendor payable invoice.",

  "DT-26":
    "Customer tax invoice (outbound AR): the tenant is the seller issuing to a customer. Shows customer as bill-to, sales line items, tax, and total receivable. Not a vendor/AP invoice or purchase order.",

  "DT-27":
    "Sales order copy issued to a customer — lists ordered items, prices, and terms. Supporting sales reference for fulfilment match; not a customer tax invoice or outbound delivery note.",

  "DT-28":
    "Outbound delivery note or dispatch docket confirming goods shipped to a customer against a sales order. Shows shipped qty and ship date — supporting fulfilment document, not a customer tax invoice or sales order.",
};

export function defaultLlmPromptForCode(code: string): string {
  return DOCUMENT_TYPE_DEFAULT_PROMPTS[code.trim().toUpperCase()] ?? "";
}

/** Every shipped matrix code that has a default prompt. */
export const SHIPPED_PROMPT_CODES = Object.keys(DOCUMENT_TYPE_DEFAULT_PROMPTS).sort();
