import type {
  DossierPipelineCheck,
  DossierPipelineEvidence,
  DossierPipelineStep,
  DossierSummary,
} from "@/lib/dossiers";
import { DOSSIER_PIPELINE_STAGES } from "@/lib/dossiers";
import {
  approvalChainBlocked,
  duplicateSkippedApprovalChain,
  importDossierApprovalChain,
  nonPoDoaApprovalChain,
  poTouchlessApprovalChain,
  poVarianceApprovalChain,
  postedPaymentHoldChain,
  suspenseMappingApprovalChain,
} from "@/lib/dossierApproval";
import {
  haltedLinkedDocuments,
  importLinkedDocuments,
  poGoodsLinkedDocuments,
  standaloneLinkedDocuments,
} from "@/lib/dossierLinkedDocuments";

type StepInput = {
  stageId: DossierPipelineStep["stageId"];
  state: DossierPipelineStep["state"];
  detail: string;
  at: string | null;
  actor?: string;
  durationMs?: number;
  exceptionCode?: string | null;
  failureReason?: string | null;
  remediation?: string | null;
  blockedReason?: string | null;
  checks?: DossierPipelineCheck[];
  evidence?: DossierPipelineEvidence[];
};

function pipeline(steps: StepInput[]): DossierPipelineStep[] {
  return steps.map((step) => ({
    stageId: step.stageId,
    state: step.state,
    detail: step.detail,
    at: step.at,
    actor: step.actor,
    durationMs: step.durationMs,
    exceptionCode: step.exceptionCode,
    failureReason: step.failureReason,
    remediation: step.remediation,
    blockedReason: step.blockedReason,
    checks: step.checks,
    evidence: step.evidence,
  }));
}

/** Shorthand for mock rows without per-check detail yet. */
function simplePipeline(
  states: Array<
    [DossierPipelineStep["stageId"], DossierPipelineStep["state"], string, string | null]
  >
): DossierPipelineStep[] {
  return pipeline(
    states.map(([stageId, state, detail, at]) => ({ stageId, state, detail, at }))
  );
}

function blockedAfter(failStage: string): string {
  return `Blocked — upstream stage "${failStage}" must pass before this stage can run.`;
}

function fullPass(detailPrefix: string): DossierPipelineStep[] {
  return pipeline([
    {
      stageId: "ingest",
      state: "pass",
      detail: `${detailPrefix} schema valid; captured 08:12`,
      at: "2026-02-03 08:12:00",
      actor: "Ingest worker",
      durationMs: 420,
      checks: [
        { id: "ing-1", label: "Capture channel allowed", state: "pass" },
        { id: "ing-2", label: "MIME / extension allowed", state: "pass" },
      ],
    },
    {
      stageId: "duplicate",
      state: "pass",
      detail: "File hash unique — no prior submission for this org",
      at: "2026-02-03 08:12:01",
      actor: "Duplicate service",
      durationMs: 35,
      checks: [
        {
          id: "dup-hash",
          label: "SHA-256 file hash",
          state: "pass",
          ruleRef: "ING-DUP",
          detail: "evaluate_file_hash_duplicate → allow",
        },
        {
          id: "dup-inflight",
          label: "No in-flight duplicate",
          state: "pass",
          ruleRef: "ING-DUP",
          expected: "No matching hash in flight",
          actual: "New hash",
        },
      ],
    },
    {
      stageId: "extract",
      state: "pass",
      detail: "parse_completed — header + 14 lines",
      at: "2026-02-03 08:12:04",
      actor: "Document intelligence",
      durationMs: 12400,
      checks: [
        { id: "ext-conf", label: "Parse confidence", state: "pass", actual: "99%" },
      ],
    },
    {
      stageId: "classify",
      state: "pass",
      detail: "document_classified · DT-01 PO goods invoice",
      at: "2026-02-03 08:12:08",
      actor: "Classifier",
      durationMs: 180,
    },
    {
      stageId: "bundle",
      state: "pass",
      detail: "playbook_evaluated — bundle 2/2",
      at: "2026-02-03 08:12:12",
      actor: "Playbook service",
      checks: [
        { id: "bun-1", label: "DT-14 PO present", state: "pass", ruleRef: "VR-PB01" },
        { id: "bun-2", label: "DT-15 GRN present", state: "pass", ruleRef: "VR-PB01" },
      ],
    },
    {
      stageId: "vendor_hold",
      state: "pass",
      detail: "Vendor registration approved — no hold",
      at: "2026-02-03 08:12:14",
      actor: "Vendor registry",
      checks: [
        {
          id: "vh-reg",
          label: "Vendor registration hold",
          state: "pass",
          ruleRef: "vendor_registration_hold",
          actual: "Not on hold",
        },
      ],
    },
    {
      stageId: "validate",
      state: "pass",
      detail: "VR01–VR15 passed",
      at: "2026-02-03 08:12:31",
      actor: "Validation runner",
      checks: [
        { id: "vr01", label: "Invoice total = subtotal + tax", state: "pass", ruleRef: "VR01" },
        { id: "vr02", label: "Business duplicate (VR02)", state: "pass", ruleRef: "VR02" },
        { id: "vr08", label: "GST arithmetic", state: "pass", ruleRef: "VR08" },
      ],
    },
    {
      stageId: "match",
      state: "pass",
      detail: "VR15 · 3-way match within PO tolerance",
      at: "2026-02-03 08:12:40",
      actor: "Match engine",
      checks: [
        {
          id: "m3",
          label: "PO qty vs GRN qty vs invoice qty",
          state: "pass",
          ruleRef: "VR15",
          expected: "200 EA",
          actual: "200 EA",
        },
        {
          id: "tol-price",
          label: "Unit price variance",
          state: "pass",
          ruleRef: "VR16",
          expected: "≤ 2%",
          actual: "0.0%",
        },
      ],
    },
    {
      stageId: "approve",
      state: "pass",
      detail: "Touchless — PO approval was the approval",
      at: "2026-02-03 08:12:50",
      actor: "Approval router",
      durationMs: 45,
      checks: [
        {
          id: "ar-touch",
          label: "Touchless policy eligible",
          state: "pass",
          ruleRef: "DOA-01",
          detail: "PO buyer approval on file satisfies DOA for this amount band",
        },
        {
          id: "ar-sod",
          label: "Segregation of duties",
          state: "pass",
          ruleRef: "DOA-02",
          detail: "Submitter ≠ approver ≠ poster",
        },
      ],
      evidence: [{ label: "PO approver", ref: "Buyer on PO-44871" }],
    },
    {
      stageId: "map_gl",
      state: "pass",
      detail: "Rule book applied · 5100 Food inventory",
      at: "2026-02-03 08:12:51",
      actor: "Rule book mapper",
      durationMs: 95,
      checks: [
        {
          id: "gl-rule",
          label: "Purchase rule matched",
          state: "pass",
          ruleRef: "PR-PO44871",
          expected: "PO code cascade",
          actual: "PO-44871 → Food inventory",
        },
        {
          id: "gl-acct",
          label: "GL account resolved",
          state: "pass",
          ruleRef: "mapping_applied",
          expected: "Not suspense",
          actual: "5100 Food inventory",
        },
        {
          id: "gl-fb",
          label: "Fallback mapping avoided",
          state: "pass",
          ruleRef: "mapper",
          detail: "rule_type: purchase_rule · match_reason: PO-44871",
        },
      ],
      evidence: [
        { label: "Account", ref: "5100" },
        { label: "Route", ref: "Purchases" },
      ],
    },
    {
      stageId: "journal",
      state: "pass",
      detail: "generate_entries — balanced journal",
      at: "2026-02-03 08:12:52",
      actor: "Journal generator",
      durationMs: 420,
      checks: [
        {
          id: "je-bal",
          label: "Journal balanced",
          state: "pass",
          ruleRef: "JE-01",
          expected: "Debits = credits",
          actual: "$13,640.00",
        },
        {
          id: "je-gst",
          label: "GST receivable line",
          state: "pass",
          ruleRef: "JE-GST",
          actual: "Dr $1,240.00",
        },
        {
          id: "je-ap",
          label: "Accounts Payable credit",
          state: "pass",
          ruleRef: "JE-AP",
          actual: "Cr $13,640.00",
        },
      ],
      evidence: [{ label: "Journal", ref: "JE-228101" }],
    },
    {
      stageId: "reconcile",
      state: "pass",
      detail: "reconcile_daily cleared",
      at: "2026-02-03 08:12:53",
      actor: "Reconciliation",
      durationMs: 220,
      checks: [
        {
          id: "rc-daily",
          label: "Daily reconciliation",
          state: "pass",
          ruleRef: "reconcile_daily",
          detail: "Sub-ledger tie-out OK for invoice date",
        },
      ],
    },
    {
      stageId: "post",
      state: "pass",
      detail: "invoice_processed · GR/IR register synced",
      at: "2026-02-03 08:12:54",
      actor: "Post service",
      durationMs: 320,
      checks: [
        {
          id: "pst-gr",
          label: "GR/IR clearing method",
          state: "pass",
          ruleRef: "DT-01",
          detail: "Dr GR/IR + Dr GST receivable / Cr Accounts Payable",
        },
        {
          id: "pst-reg",
          label: "Purchase register synced",
          state: "pass",
          ruleRef: "sync_purchase_document",
          actual: "PO-44871 · Matched",
        },
        {
          id: "pst-proc",
          label: "invoice_processed",
          state: "pass",
          ruleRef: "pipeline",
          actual: "status: processed",
        },
      ],
      evidence: [
        { label: "Method", ref: "GR/IR" },
        { label: "3-way", ref: "Matched" },
      ],
    },
    {
      stageId: "pay",
      state: "pass",
      detail: "Queued EFT, net 30",
      at: "2026-02-03 08:12:56",
      actor: "Payments queue",
      durationMs: 120,
      checks: [
        {
          id: "pay-vnd",
          label: "Vendor not on payment block list",
          state: "pass",
          ruleRef: "PAY-01",
        },
        {
          id: "pay-bank",
          label: "Bank details verified",
          state: "pass",
          ruleRef: "PAY-04",
        },
        {
          id: "pay-dup",
          label: "Payment duplicate scan",
          state: "pass",
          ruleRef: "PAY-03",
        },
      ],
      evidence: [
        { label: "Payment ref", ref: "PAY-7781" },
        { label: "Terms", ref: "Net 30 EFT" },
      ],
    },
    {
      stageId: "archive",
      state: "pass",
      detail: "WORM archived, linked to JE-228101",
      at: "2026-02-03 08:12:55",
      actor: "Archive",
      durationMs: 210,
      checks: [
        {
          id: "arc-worm",
          label: "WORM retention seal",
          state: "pass",
          ruleRef: "ARC-01",
          expected: "AU 5y minimum",
          actual: "Sealed",
        },
        {
          id: "arc-je",
          label: "Linked to journal entry",
          state: "pass",
          ruleRef: "ARC-02",
          actual: "JE-228101",
        },
      ],
    },
  ]);
}

export const DOSSIER_MOCK_CATALOG: DossierSummary[] = [
  {
    id: "DOS-0401",
    documentTypeCode: "DT-01",
    documentTypeTitle: "PO-based goods invoice",
    vendor: "Meridian Foods Pty Ltd",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558210",
    captureChannel: "EDI capture",
    invoiceDate: "2026-02-02",
    currency: "AUD",
    subtotal: 12400,
    tax: 1240,
    total: 13640,
    classificationLabel: "Transactional",
    classificationConfidence: 99,
    fraudRisk: "low",
    poReference: "PO-44871",
    slaLabel: "Posted",
    slaBreached: false,
    owner: "System",
    outcome: "auto_posted",
    outcomeBanner: "Perfect 3-way match — touchless auto-post.",
    linkedDocuments: poGoodsLinkedDocuments({
      poReference: "PO-44871",
      anchorDossierId: "DOS-0401",
      anchorRef: "INV-558210",
      po: { present: true, ref: "PO-44871", source: "erp_register" },
      grn: { present: true, ref: "GRN-90233", source: "erp_register" },
      purchaseOrderId: 44871,
      match: {
        status: "3-Way Match",
        poValue: 12400,
        invoiceTotal: 13640,
        deviation: 0,
        currency: "AUD",
      },
    }),
    pipeline: fullPass("EDI 810"),
    approvalChain: poTouchlessApprovalChain({
      poBuyer: "Buyer on PO-44871",
      exceptionActor: "System",
      exceptionAt: "2026-02-03 08:12:52",
      published: true,
      publishedAt: "2026-02-03 08:12:54",
      paymentState: "done",
      paymentAt: "2026-02-03 08:12:56",
      total: 13640,
      currency: "AUD",
    }),
  },
  {
    id: "DOS-0402",
    documentTypeCode: "DT-01",
    documentTypeTitle: "PO-based goods invoice",
    vendor: "Sysco Foods Australia Pty Ltd",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558211",
    captureChannel: "Email capture",
    invoiceDate: "2026-02-01",
    currency: "AUD",
    subtotal: 8200,
    tax: 820,
    total: 9020,
    classificationLabel: "Transactional",
    classificationConfidence: 96,
    fraudRisk: "low",
    poReference: "PO-44890",
    slaLabel: "Blocked",
    slaBreached: true,
    owner: "AP queue",
    outcome: "blocked",
    outcomeBanner: "GRN missing — 3-way match cannot complete.",
    linkedDocuments: poGoodsLinkedDocuments({
      poReference: "PO-44890",
      anchorDossierId: "DOS-0402",
      anchorRef: "INV-558211",
      po: { present: true, ref: "PO-44890", source: "erp_register" },
      grn: { present: false },
      purchaseOrderId: 44890,
      match: {
        status: "No GRN",
        poValue: 8200,
        invoiceTotal: 9020,
        deviation: 820,
        currency: "AUD",
      },
    }),
    pipeline: pipeline([
      {
        stageId: "ingest",
        state: "pass",
        detail: "email_ingested from accounts@sysco.com.au",
        at: "2026-02-02 09:04:00",
        actor: "Email ingest",
        durationMs: 890,
        evidence: [{ label: "Source mailbox", ref: "accounts@sysco.com.au" }],
      },
      {
        stageId: "duplicate",
        state: "pass",
        detail: "File hash unique",
        at: "2026-02-02 09:04:01",
        actor: "Duplicate service",
        checks: [
          { id: "dup-hash", label: "SHA-256 file hash", state: "pass", ruleRef: "ING-DUP" },
        ],
      },
      {
        stageId: "extract",
        state: "pass",
        detail: "parse_completed — header + 8 lines",
        at: "2026-02-02 09:04:04",
        actor: "Document intelligence",
        durationMs: 9800,
      },
      {
        stageId: "classify",
        state: "pass",
        detail: "document_classified · DT-01",
        at: "2026-02-02 09:04:06",
        actor: "Classifier",
        durationMs: 210,
      },
      {
        stageId: "bundle",
        state: "fail",
        detail: "playbook_evaluated — GRN missing (1/2)",
        at: "2026-02-02 09:04:10",
        actor: "Playbook service",
        exceptionCode: "BUNDLE_INCOMPLETE",
        failureReason:
          "Playbook DT-01 requires PO + goods receipt before posting. GRN member DT-15 is missing.",
        remediation:
          "Upload or link goods receipt GRN for PO-44890, or request buyer to confirm receipt in ERP.",
        checks: [
          {
            id: "bun-po",
            label: "DT-14 Purchase order linked",
            state: "pass",
            ruleRef: "VR-PB01",
            detail: "PO-44890 found in dossier",
          },
          {
            id: "bun-grn",
            label: "DT-15 Goods receipt linked",
            state: "fail",
            ruleRef: "VR-PB01",
            expected: "GRN for PO-44890",
            actual: "Not present",
            detail: "No GRN document uploaded or matched by linkage key",
          },
        ],
        evidence: [
          { label: "PO", ref: "PO-44890" },
          { label: "Missing", ref: "DT-15 GRN" },
        ],
      },
      {
        stageId: "vendor_hold",
        state: "pass",
        detail: "Vendor approved — no hold",
        at: "2026-02-02 09:04:32",
        actor: "Vendor registry",
      },
      {
        stageId: "validate",
        state: "pass",
        detail: "validation_passed",
        at: "2026-02-02 09:04:35",
        actor: "Validation runner",
        checks: [
          { id: "vr01", label: "Invoice total = subtotal + tax", state: "pass", ruleRef: "VR01" },
          { id: "vr08", label: "GST arithmetic", state: "pass", ruleRef: "VR08" },
        ],
      },
      {
        stageId: "match",
        state: "fail",
        detail: "Cannot match — no GRN for PO-44890",
        at: "2026-02-02 09:04:42",
        actor: "Match engine",
        exceptionCode: "MATCH_NO_GRN",
        failureReason: "3-way match requires received quantity from GRN. Without GRN, invoice qty cannot be verified.",
        remediation: "Resolve bundle failure first, then re-run match from Exceptions queue.",
        checks: [
          {
            id: "m-po",
            label: "Invoice references open PO",
            state: "pass",
            ruleRef: "VR-M01",
            expected: "PO-44890 open",
            actual: "PO-44890 open",
          },
          {
            id: "m-grn",
            label: "GRN qty available for match",
            state: "fail",
            ruleRef: "VR-M03",
            expected: "GRN lines for PO-44890",
            actual: "0 GRN lines",
          },
          {
            id: "m-qty",
            label: "Invoice qty ≤ received qty",
            state: "skipped",
            ruleRef: "VR-M04",
            detail: "Skipped — prerequisite GRN check failed",
          },
        ],
      },
      {
        stageId: "approve",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "map_gl",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "journal",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "reconcile",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "post",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "pay",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "archive",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
    ]),
    approvalChain: approvalChainBlocked({
      policyMode: "touchless_on_clean_match",
      blockedAfter: "Bundle / playbook",
      total: 9020,
      currency: "AUD",
    }),
  },
  {
    id: "DOS-0403",
    documentTypeCode: "DT-10",
    documentTypeTitle: "Import dossier",
    vendor: "Global Freight Co.",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558220",
    captureChannel: "Upload",
    invoiceDate: "2026-01-28",
    currency: "AUD",
    subtotal: 45200,
    tax: 4520,
    total: 49720,
    classificationLabel: "Transactional",
    classificationConfidence: 91,
    fraudRisk: "medium",
    poReference: "SHP-991",
    slaLabel: "Blocked",
    slaBreached: true,
    owner: "Import desk",
    outcome: "blocked",
    outcomeBanner: "Blocking bundle incomplete — customs entry and packing list missing.",
    linkedDocuments: importLinkedDocuments({
      shipmentRef: "SHP-991",
      anchorDossierId: "DOS-0403",
      anchorRef: "INV-558220",
      advisories: ["Certificate of origin recommended for duty rebate"],
      members: [
        { code: "DT-10", label: "Commercial invoice", ref: "INV-558220", present: true, source: "upload" },
        { code: "DT-11", label: "Customs entry", present: false },
        { code: "DT-12", label: "Bill of lading", ref: "BL-4402", present: true, source: "email_capture" },
        { code: "DT-13", label: "Packing list", present: false },
        { code: "DT-16", label: "Duty receipt", present: false },
        { code: "DT-17", label: "Transport doc", ref: "AWB-7781", present: true, source: "upload" },
      ],
    }),
    pipeline: simplePipeline([
      ["ingest", "pass", "Commercial invoice PDF uploaded", "2026-01-29 11:20:00"],
      ["duplicate", "pass", "File hash unique", "2026-01-29 11:20:01"],
      ["extract", "pass", "parse_completed — landed-cost fields", "2026-01-29 11:20:03"],
      ["classify", "pass", "DT-10 Import dossier — conf 0.91", "2026-01-29 11:20:05"],
      ["bundle", "fail", "playbook_evaluated — bundle 3/6", "2026-01-29 11:20:12"],
      ["vendor_hold", "pending", "—", null],
      ["validate", "fail", "VR-PB02 mandatory bundle members missing", "2026-01-29 11:20:55"],
      ["match", "pending", "—", null],
      ["approve", "pending", "—", null],
      ["map_gl", "pending", "—", null],
      ["journal", "pending", "—", null],
      ["reconcile", "pending", "—", null],
      ["post", "pending", "—", null],
      ["pay", "pending", "—", null],
      ["archive", "pending", "—", null],
    ]),
    approvalChain: importDossierApprovalChain({}),
  },
  {
    id: "DOS-0404",
    documentTypeCode: "DT-01",
    documentTypeTitle: "PO-based goods invoice",
    vendor: "OfficeMax Australia",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558230",
    captureChannel: "Upload",
    invoiceDate: "2026-02-03",
    currency: "AUD",
    subtotal: 3100,
    tax: 310,
    total: 3410,
    classificationLabel: "Transactional",
    classificationConfidence: 94,
    fraudRisk: "low",
    poReference: "PO-44910",
    slaLabel: "Review",
    slaBreached: false,
    owner: "Marcus Webb",
    outcome: "blocked",
    outcomeBanner: "Price variance exceeds tolerance on line 2 — buyer approval required.",
    linkedDocuments: poGoodsLinkedDocuments({
      poReference: "PO-44910",
      anchorDossierId: "DOS-0404",
      anchorRef: "INV-558230",
      po: { present: true, ref: "PO-44910", source: "erp_register" },
      grn: { present: true, ref: "GRN-90255", source: "erp_register" },
      purchaseOrderId: 44910,
      match: {
        status: "Price Variance",
        poValue: 3100,
        invoiceTotal: 3410,
        deviation: 124,
        currency: "AUD",
      },
    }),
    pipeline: pipeline([
      {
        stageId: "ingest",
        state: "pass",
        detail: "PDF uploaded via workspace",
        at: "2026-02-03 14:02:00",
        actor: "Upload capture",
        durationMs: 420,
      },
      {
        stageId: "duplicate",
        state: "pass",
        detail: "File hash unique",
        at: "2026-02-03 14:02:01",
        actor: "Duplicate service",
      },
      {
        stageId: "extract",
        state: "pass",
        detail: "parse_completed — header + 3 lines",
        at: "2026-02-03 14:02:03",
        actor: "Document intelligence",
        durationMs: 6200,
      },
      {
        stageId: "classify",
        state: "pass",
        detail: "document_classified · DT-01",
        at: "2026-02-03 14:02:05",
        actor: "Classifier",
        durationMs: 180,
      },
      {
        stageId: "bundle",
        state: "pass",
        detail: "playbook_evaluated — bundle 2/2",
        at: "2026-02-03 14:02:09",
        actor: "Playbook service",
        checks: [
          { id: "b-po", label: "DT-14 Purchase order", state: "pass", ruleRef: "VR-PB01", actual: "PO-44910" },
          { id: "b-grn", label: "DT-15 Goods receipt", state: "pass", ruleRef: "VR-PB01", actual: "GRN-90255" },
        ],
      },
      {
        stageId: "vendor_hold",
        state: "pass",
        detail: "Vendor approved — no hold",
        at: "2026-02-03 14:02:22",
        actor: "Vendor registry",
      },
      {
        stageId: "validate",
        state: "pass",
        detail: "validation_passed",
        at: "2026-02-03 14:02:28",
        actor: "Validation runner",
        checks: [
          { id: "vr01", label: "Invoice total = subtotal + tax", state: "pass", ruleRef: "VR01" },
          { id: "vr02", label: "Business duplicate (VR02)", state: "pass", ruleRef: "VR02" },
          { id: "vr08", label: "GST arithmetic", state: "pass", ruleRef: "VR08" },
        ],
      },
      {
        stageId: "match",
        state: "fail",
        detail: "VR16 · unit price +4.2% above PO cap on line 2",
        at: "2026-02-03 14:02:36",
        actor: "Match engine",
        exceptionCode: "MATCH_PRICE_VARIANCE",
        failureReason:
          "Line 2 unit price $42.50 exceeds PO-44910 negotiated cap $40.78 by 4.2%. Variance workflow requires buyer approval before mapping.",
        remediation:
          "Request buyer approval for price variance, or ask vendor for credit note / revised invoice at PO price.",
        checks: [
          {
            id: "m-po",
            label: "Invoice references open PO",
            state: "pass",
            ruleRef: "VR15",
            expected: "PO-44910 open",
            actual: "PO-44910 open",
          },
          {
            id: "m-grn",
            label: "GRN qty available for match",
            state: "pass",
            ruleRef: "VR15",
            expected: "GRN lines for PO-44910",
            actual: "3 GRN lines",
          },
          {
            id: "m-price",
            label: "Unit price within PO tolerance",
            state: "fail",
            ruleRef: "VR16",
            expected: "≤ $40.78 (PO line 2)",
            actual: "$42.50 (+4.2%)",
            detail: "Office supplies — toner cartridge SKU OFF-9921",
          },
        ],
        evidence: [
          { label: "PO line 2", ref: "$40.78 cap" },
          { label: "Invoice line 2", ref: "$42.50" },
        ],
      },
      {
        stageId: "approve",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "map_gl",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "journal",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "reconcile",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "post",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "pay",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
      {
        stageId: "archive",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Match"),
      },
    ]),
    approvalChain: poVarianceApprovalChain({
      buyer: "Marcus Webb",
      varianceDetail: "Line 2 unit price $42.50 exceeds PO-44910 cap $40.78 by 4.2%",
      total: 3410,
      currency: "AUD",
    }),
  },
  {
    id: "DOS-0405",
    documentTypeCode: "DT-02",
    documentTypeTitle: "Non-PO invoice",
    vendor: "City Water Pty Ltd",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558240",
    captureChannel: "Email capture",
    invoiceDate: "2026-02-02",
    currency: "AUD",
    subtotal: 890,
    tax: 89,
    total: 979,
    classificationLabel: "Transactional",
    classificationConfidence: 97,
    fraudRisk: "low",
    poReference: null,
    slaLabel: "Posted",
    slaBreached: false,
    owner: "System",
    outcome: "auto_posted",
    outcomeBanner: "Non-PO utility — coded to Utilities per category rule.",
    linkedDocuments: standaloneLinkedDocuments({
      anchorDossierId: "DOS-0405",
      code: "DT-02",
      label: "Utility invoice",
      ref: "INV-558240",
      source: "email_capture",
    }),
    pipeline: fullPass("Email"),
    approvalChain: nonPoDoaApprovalChain({
      approver: "Policy engine",
      approverRole: "Manager",
      gateState: "waived",
      published: true,
      publishedAt: "2026-02-02 16:10:12",
      paymentState: "done",
      paymentAt: "2026-02-02 16:10:14",
      total: 979,
      currency: "AUD",
    }),
  },
  {
    id: "DOS-0406",
    documentTypeCode: "DT-01",
    documentTypeTitle: "PO-based goods invoice",
    vendor: "Bidfood Australia",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558250",
    captureChannel: "EDI capture",
    invoiceDate: "2026-02-03",
    currency: "AUD",
    subtotal: 22100,
    tax: 2210,
    total: 24310,
    classificationLabel: "Transactional",
    classificationConfidence: 98,
    fraudRisk: "low",
    poReference: "PO-44922",
    slaLabel: "Processing",
    slaBreached: false,
    owner: "System",
    outcome: "blocked",
    outcomeBanner: "mapping_review_required — rule book could not resolve GL; suspense mapping blocked.",
    linkedDocuments: poGoodsLinkedDocuments({
      poReference: "PO-44922",
      anchorDossierId: "DOS-0406",
      anchorRef: "INV-558250",
      po: { present: true, ref: "PO-44922", source: "edi" },
      grn: { present: true, ref: "GRN-90260", source: "erp_register" },
      purchaseOrderId: 44922,
      match: {
        status: "3-Way Match",
        poValue: 22100,
        invoiceTotal: 24310,
        deviation: 0,
        currency: "AUD",
      },
    }),
    pipeline: pipeline([
      {
        stageId: "ingest",
        state: "pass",
        detail: "EDI 810 ingested",
        at: "2026-02-03 10:00:00",
        actor: "EDI ingest",
      },
      {
        stageId: "duplicate",
        state: "pass",
        detail: "File hash unique",
        at: "2026-02-03 10:00:01",
        actor: "Duplicate service",
      },
      {
        stageId: "extract",
        state: "pass",
        detail: "parse_completed — 22 lines",
        at: "2026-02-03 10:00:03",
        actor: "Document intelligence",
      },
      {
        stageId: "classify",
        state: "pass",
        detail: "document_classified · DT-01",
        at: "2026-02-03 10:00:04",
        actor: "Classifier",
      },
      {
        stageId: "bundle",
        state: "pass",
        detail: "playbook_evaluated — bundle 2/2",
        at: "2026-02-03 10:00:08",
        actor: "Playbook service",
      },
      {
        stageId: "vendor_hold",
        state: "pass",
        detail: "Vendor approved — no hold",
        at: "2026-02-03 10:00:38",
        actor: "Vendor registry",
      },
      {
        stageId: "validate",
        state: "pass",
        detail: "validation_passed",
        at: "2026-02-03 10:00:42",
        actor: "Validation runner",
      },
      {
        stageId: "match",
        state: "pass",
        detail: "VR15 · 3-way match OK",
        at: "2026-02-03 10:00:50",
        actor: "Match engine",
      },
      {
        stageId: "approve",
        state: "pass",
        detail: "Touchless — within policy",
        at: "2026-02-03 10:01:02",
        actor: "Approval router",
      },
      {
        stageId: "map_gl",
        state: "fail",
        detail: "Rule book applied · Suspense Account",
        at: "2026-02-03 10:01:08",
        actor: "Rule book mapper",
        exceptionCode: "MAP_SUSPENSE",
        failureReason:
          "No purchase rule, vendor rule, or keyword rule matched for line descriptions. Fallback suspense mapping requires GL review per routing_review_service.",
        remediation:
          "Add or fix a purchase rule for this vendor/PO in Rule book → Purchases, then reprocess from Exceptions.",
        checks: [
          {
            id: "gl-po",
            label: "PO code cascade",
            state: "fail",
            ruleRef: "cascade",
            expected: "PO-44922 rule",
            actual: "No match",
          },
          {
            id: "gl-vnd",
            label: "Vendor rule",
            state: "fail",
            ruleRef: "cascade",
            expected: "Bidfood Australia",
            actual: "No match",
          },
          {
            id: "gl-susp",
            label: "Suspense fallback",
            state: "fail",
            ruleRef: "mapping_review_required",
            expected: "Explicit GL account",
            actual: "Suspense Account",
          },
        ],
        evidence: [
          { label: "route_target", ref: "purchases" },
          { label: "rule_type", ref: "fallback" },
        ],
      },
      {
        stageId: "journal",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Map GL"),
      },
      {
        stageId: "reconcile",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Map GL"),
      },
      {
        stageId: "post",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Map GL"),
      },
      {
        stageId: "pay",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Map GL"),
      },
      {
        stageId: "archive",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Map GL"),
      },
    ]),
    approvalChain: suspenseMappingApprovalChain({ total: 24310, currency: "AUD" }),
  },
  {
    id: "DOS-0407",
    documentTypeCode: "DT-02",
    documentTypeTitle: "Non-PO invoice",
    vendor: "BuildRight Construction",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558260",
    captureChannel: "Upload",
    invoiceDate: "2026-01-30",
    currency: "AUD",
    subtotal: 40000,
    tax: 4000,
    total: 44000,
    classificationLabel: "Transactional",
    classificationConfidence: 93,
    fraudRisk: "medium",
    poReference: null,
    slaLabel: "Posted",
    slaBreached: false,
    owner: "Contract owner",
    outcome: "manual_posted",
    outcomeBanner: "Construction retention — post gross, credit retention payable (DT-02).",
    linkedDocuments: standaloneLinkedDocuments({
      anchorDossierId: "DOS-0407",
      code: "DT-02",
      label: "Progress invoice",
      ref: "INV-558260",
      source: "upload",
      contractRef: "CNT-BR-2201",
      supporting: [
        {
          code: "DT-18",
          label: "Milestone certificate",
          ref: "MS-2201",
          present: true,
          requirement: "mandatory",
        },
      ],
    }),
    pipeline: simplePipeline([
      ["ingest", "pass", "PDF uploaded via workspace", "2026-01-31 10:00:00"],
      ["duplicate", "pass", "File hash unique", "2026-01-31 10:00:01"],
      ["extract", "pass", "parse_completed", "2026-01-31 10:00:03"],
      ["classify", "pass", "DT-02 Non-PO invoice — conf 0.93", "2026-01-31 10:00:05"],
      ["bundle", "pass", "playbook_evaluated", "2026-01-31 10:00:10"],
      ["validate", "pass", "Retention rule applied", "2026-01-31 10:00:35"],
      ["vendor_hold", "pass", "Vendor approved — no hold", "2026-01-31 10:00:38"],
      ["match", "waived", "Non-PO — match not required", "2026-01-31 10:00:40"],
      ["approve", "pass", "Contract owner approved", "2026-01-31 11:15:00"],
      ["map_gl", "pass", "mapping_applied · 4200 WIP / retention", "2026-01-31 11:15:05"],
      ["journal", "pass", "generate_entries — retention holdback", "2026-01-31 11:15:12"],
      ["reconcile", "pass", "reconcile_daily cleared", "2026-01-31 11:15:15"],
      ["post", "pass", "invoice_processed", "2026-01-31 11:15:18"],
      ["pay", "pending", "Awaiting payment run", null],
      ["archive", "pass", "WORM archived, linked to JE-228090", "2026-01-31 11:15:35"],
    ]),
    approvalChain: nonPoDoaApprovalChain({
      approver: "P. Nguyen",
      approverRole: "Contract owner",
      gateState: "done",
      approvedAt: "2026-01-31 11:14:55",
      published: true,
      publishedAt: "2026-01-31 11:15:18",
      paymentState: "pending",
      total: 44000,
      currency: "AUD",
    }),
  },
  {
    id: "DOS-0408",
    documentTypeCode: "DT-01",
    documentTypeTitle: "PO-based goods invoice",
    vendor: "Harbour Linen Supply",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "HL-22019",
    captureChannel: "Email capture",
    invoiceDate: "2026-02-01",
    currency: "AUD",
    subtotal: 1850,
    tax: 185,
    total: 2035,
    classificationLabel: "Transactional",
    classificationConfidence: 97,
    fraudRisk: "low",
    poReference: "PO-44855",
    slaLabel: "Parked",
    slaBreached: false,
    owner: "AP queue",
    outcome: "parked",
    outcomeBanner: "Parked pending vendor bank detail verification.",
    linkedDocuments: poGoodsLinkedDocuments({
      poReference: "PO-44855",
      anchorDossierId: "DOS-0408",
      anchorRef: "HL-22019",
      po: { present: true, ref: "PO-44855", source: "erp_register" },
      grn: { present: true, ref: "GRN-90240", source: "erp_register" },
      purchaseOrderId: 44855,
      match: {
        status: "3-Way Match",
        poValue: 1850,
        invoiceTotal: 2035,
        deviation: 0,
        currency: "AUD",
      },
    }),
    pipeline: pipeline([
      {
        stageId: "ingest",
        state: "pass",
        detail: "PDF from billing@harbourlinen.com.au",
        at: "2026-02-03 09:40:00",
        actor: "Email ingest",
      },
      {
        stageId: "duplicate",
        state: "pass",
        detail: "File hash unique",
        at: "2026-02-03 09:40:01",
        actor: "Duplicate service",
      },
      {
        stageId: "extract",
        state: "pass",
        detail: "parse_completed — header + 4 lines",
        at: "2026-02-03 09:40:03",
        actor: "Document intelligence",
      },
      {
        stageId: "classify",
        state: "pass",
        detail: "document_classified · DT-01",
        at: "2026-02-03 09:40:05",
        actor: "Classifier",
      },
      {
        stageId: "bundle",
        state: "pass",
        detail: "playbook_evaluated — bundle 2/2",
        at: "2026-02-03 09:40:10",
        actor: "Playbook service",
      },
      {
        stageId: "vendor_hold",
        state: "pass",
        detail: "Vendor approved — no hold",
        at: "2026-02-03 09:40:24",
        actor: "Vendor registry",
      },
      {
        stageId: "validate",
        state: "pass",
        detail: "validation_passed",
        at: "2026-02-03 09:40:30",
        actor: "Validation runner",
      },
      {
        stageId: "match",
        state: "pass",
        detail: "VR15 · 3-way match OK",
        at: "2026-02-03 09:40:38",
        actor: "Match engine",
      },
      {
        stageId: "approve",
        state: "pass",
        detail: "Touchless — within policy",
        at: "2026-02-03 09:40:42",
        actor: "Approval router",
      },
      {
        stageId: "map_gl",
        state: "pass",
        detail: "mapping_applied · 5200 Linen COGS",
        at: "2026-02-03 09:40:46",
        actor: "Rule book mapper",
        checks: [
          {
            id: "gl-acct",
            label: "GL account resolved",
            state: "pass",
            ruleRef: "mapping_applied",
            actual: "5200 Linen COGS",
          },
        ],
      },
      {
        stageId: "journal",
        state: "pass",
        detail: "generate_entries complete",
        at: "2026-02-03 09:40:50",
        actor: "Journal generator",
      },
      {
        stageId: "reconcile",
        state: "pass",
        detail: "reconcile_daily cleared",
        at: "2026-02-03 09:40:52",
        actor: "Reconciliation",
      },
      {
        stageId: "post",
        state: "pass",
        detail: "Posted GR/IR method",
        at: "2026-02-03 09:40:50",
        actor: "Post service",
        evidence: [{ label: "Journal", ref: "JE-228095" }],
      },
      {
        stageId: "pay",
        state: "fail",
        detail: "Parked — bank details unverified",
        at: "2026-02-03 09:40:55",
        actor: "Payments queue",
        exceptionCode: "PAY_BANK_HOLD",
        failureReason:
          "Vendor BSB/account changed since last payment. Bank freeze policy requires AP to verify call-back before EFT.",
        remediation:
          "Complete vendor bank verification in Vendors tab, then release from Payments queue.",
        checks: [
          { id: "pay-vnd", label: "Vendor not on block list", state: "pass", ruleRef: "PAY-01" },
          {
            id: "pay-bank",
            label: "Bank details verified",
            state: "fail",
            ruleRef: "PAY-04",
            expected: "Verified BSB 062-000",
            actual: "Pending call-back",
          },
          { id: "pay-san", label: "Sanctions re-screen", state: "pass", ruleRef: "PAY-05" },
        ],
      },
      {
        stageId: "archive",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Pay"),
      },
    ]),
    approvalChain: postedPaymentHoldChain({
      invoiceApprover: "Policy engine",
      total: 2035,
      currency: "AUD",
      paymentDetail: "Bank details unverified — PAY-04 hold",
    }),
  },
  {
    id: "DOS-0409",
    documentTypeCode: "DT-01",
    documentTypeTitle: "PO-based goods invoice",
    vendor: "PFD Food Services",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558270",
    captureChannel: "EDI capture",
    invoiceDate: "2026-02-03",
    currency: "AUD",
    subtotal: 15600,
    tax: 1560,
    total: 17160,
    classificationLabel: "Transactional",
    classificationConfidence: 98,
    fraudRisk: "low",
    poReference: "PO-44930",
    slaLabel: "Posted",
    slaBreached: false,
    owner: "System",
    outcome: "auto_posted",
    outcomeBanner: "Touchless auto-post — within tolerance.",
    linkedDocuments: poGoodsLinkedDocuments({
      poReference: "PO-44930",
      anchorDossierId: "DOS-0409",
      anchorRef: "INV-558270",
      po: { present: true, ref: "PO-44930", source: "edi" },
      grn: { present: true, ref: "GRN-90265", source: "erp_register" },
      purchaseOrderId: 44930,
      match: {
        status: "3-Way Match",
        poValue: 15600,
        invoiceTotal: 17160,
        deviation: 0,
        currency: "AUD",
      },
    }),
    pipeline: fullPass("EDI 810"),
    approvalChain: poTouchlessApprovalChain({
      poBuyer: "Buyer on PO-44930",
      exceptionActor: "System",
      exceptionAt: "2026-02-03 11:22:10",
      published: true,
      publishedAt: "2026-02-03 11:22:12",
      paymentState: "done",
      paymentAt: "2026-02-03 11:22:14",
      total: 17160,
      currency: "AUD",
    }),
  },
  {
    id: "DOS-0410",
    documentTypeCode: "DT-01",
    documentTypeTitle: "PO-based goods invoice",
    vendor: "Meridian Foods Pty Ltd",
    buyer: "Acme Hospitality Pty Ltd",
    invoiceRef: "INV-558210",
    captureChannel: "Email capture",
    invoiceDate: "2026-02-04",
    currency: "AUD",
    subtotal: 12400,
    tax: 1240,
    total: 13640,
    classificationLabel: "Transactional",
    classificationConfidence: 0,
    fraudRisk: "low",
    poReference: "PO-44871",
    slaLabel: "Blocked",
    slaBreached: false,
    owner: "AP queue",
    outcome: "blocked",
    outcomeBanner: "Duplicate file — same PDF already ingested as DOS-0401.",
    linkedDocuments: haltedLinkedDocuments({
      poReference: "PO-44871",
      anchorDossierId: "DOS-0410",
      anchorRef: "INV-558210",
      reason: "duplicate_skipped — bundle not evaluated",
    }),
    pipeline: pipeline([
      {
        stageId: "ingest",
        state: "pass",
        detail: "email_ingested — attachment invoice_feb.pdf",
        at: "2026-02-04 07:55:00",
        actor: "Email ingest",
        durationMs: 620,
        evidence: [{ label: "Mailbox", ref: "ap@acme.com.au" }],
      },
      {
        stageId: "duplicate",
        state: "fail",
        detail: "duplicate_skipped — file hash matches prior submission",
        at: "2026-02-04 07:55:01",
        actor: "Duplicate service",
        exceptionCode: "DUPLICATE_FILE",
        failureReason:
          "SHA-256 hash matches invoice already on file (DOS-0401 / INV-558210). Re-ingest rejected before parse.",
        remediation:
          "If this is a corrected invoice, upload a new file or use the re-ingest workflow from the original dossier.",
        checks: [
          {
            id: "dup-hash",
            label: "SHA-256 file hash",
            state: "fail",
            ruleRef: "ING-DUP",
            expected: "Unique hash for org",
            actual: "Matches DOS-0401",
            detail: "evaluate_file_hash_duplicate → duplicate_skipped",
          },
          {
            id: "dup-prior",
            label: "Prior dossier on file",
            state: "fail",
            ruleRef: "ING-DUP",
            expected: "No active duplicate",
            actual: "DOS-0401",
          },
        ],
        evidence: [
          { label: "Prior dossier", ref: "DOS-0401" },
          { label: "Hash", ref: "a3f8…c21d" },
        ],
      },
      {
        stageId: "extract",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "classify",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "bundle",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "vendor_hold",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "validate",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "match",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "approve",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "map_gl",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "journal",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "reconcile",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "post",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "pay",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
      {
        stageId: "archive",
        state: "pending",
        detail: "—",
        at: null,
        blockedReason: blockedAfter("Duplicate file check"),
      },
    ]),
    approvalChain: duplicateSkippedApprovalChain(),
  },
];

export const DOSSIER_RECENT_LIMIT = 12;

export function sortDossiersNewestFirst(rows: DossierSummary[]): DossierSummary[] {
  return [...rows].sort((a, b) => {
    const byDate = b.invoiceDate.localeCompare(a.invoiceDate);
    if (byDate !== 0) return byDate;
    return b.id.localeCompare(a.id);
  });
}

/** Newest dossiers first — capped for hero grid (matches upload recent list pattern). */
export function recentDossierCatalog(limit = DOSSIER_RECENT_LIMIT): DossierSummary[] {
  return sortDossiersNewestFirst(DOSSIER_MOCK_CATALOG).slice(0, limit);
}

export function getDossierById(id: string): DossierSummary | undefined {
  return DOSSIER_MOCK_CATALOG.find((row) => row.id === id);
}

export function dossierDocumentTypeOptions(): Array<{ value: string; label: string }> {
  const codes = [...new Set(DOSSIER_MOCK_CATALOG.map((row) => row.documentTypeCode))].sort();
  return [
    { value: "all", label: "All document types" },
    ...codes.map((code) => {
      const row = DOSSIER_MOCK_CATALOG.find((d) => d.documentTypeCode === code);
      return { value: code, label: row ? `${code} · ${row.documentTypeTitle}` : code };
    }),
  ];
}

if (import.meta.env.DEV) {
  for (const dossier of DOSSIER_MOCK_CATALOG) {
    const present = new Set(dossier.pipeline.map((step) => step.stageId));
    const missing = DOSSIER_PIPELINE_STAGES.filter((stage) => !present.has(stage.id));
    if (missing.length > 0) {
      console.warn(
        `[dossiers] ${dossier.id} missing pipeline stages:`,
        missing.map((s) => s.id).join(", ")
      );
    }
  }
}
